var BASEDIR = "/";
var LANG = "en-US";
var APP_ID = "1";
var APP_SHORTNAME = "firefox";
var APP_PRETTYNAME = "Firefox";
var LATEST_FIREFOX_VERSION = '3.0.11';
var LATEST_FIREFOX_DEVEL_VERSION = '3.5b4';
var APP_FIREFOX = '1';
var APP_SEAMONKEY = '59';
var APP_THUNDERBIRD = '18';
var APP_SUNBIRD = '52';
var APP_FENNEC = '60';
var KEYCODE_ENTER = 13;
var addOnNotAvailableForPlatform = "%1$s is not available for %2$s.";
var error_opensearch_unsupported = "Sorry, you need a Mozilla-based browser (such as Firefox) to install a search plugin.";
var app_compat_update_firefox = "<a href=\"http://getfirefox.com\">Upgrade Firefox</a> to use this add-on";
var app_compat_try_old_version = "An <a href=\"%1$s\">older version</a> may work";
var app_compat_older_firefox_only = "This add-on is for older versions of Firefox";
var app_compat_unreleased_version = "This add-on requires the not-yet released <a href=\"%1$s\">Firefox %2$s</a>";
var app_compat_older_version_or_ignore_check = "You can <a href=\"%1$s\">try an older version</a> or <a href=\"#\" onclick=\"%2$s\">ignore this check</a>";
var devcp_js_upload_alert = "You must select a file to upload.";
var addons_status_public = "Public";
var addons_status_sandbox = "In Sandbox";
var addons_status_pending = "In Sandbox; Pending Review";
var devcp_js_img_move_down = "Move Down";
var devcp_js_img_move_up = "Move Up";
var devcp_js_option_owner = "Owner";
var devcp_js_option_developer = "Developer";
var devcp_js_option_viewer = "Viewer";
var devcp_js_input_list_author = "List as author in public listings";
var devcp_js_sure_remove = "Are you <strong>sure</strong> you wish to remove this author?";
var devcp_js_remove_author = "Remove Author";
var devcp_js_a_cancel = "Cancel";
var devcp_js_add_email = "Please enter the account email of the author you wish to add.";
var devcp_js_img_remove_compat = "Remove Application Compatibility";
var devcp_js_license_select = "Please select a license.";
var devcp_js_license_text = "Please enter text for your license.";
var app_compat_ignore_check = "Ignore version check";
var collections_edit_submit = "Update Collection";
var collections_edit_submit_deletecollection = "Delete Collection";
var addons_display_collection_publish_success = "%1$s has been added to the %2$s collection.";
