var BASEDIR = "/";
var LANG = "en-US";
var APP_ID = "1";
var APP_SHORTNAME = "firefox";
var APP_PRETTYNAME = "Firefox";
var LATEST_FIREFOX_VERSION = '3.0.11';
var LATEST_FIREFOX_DEVEL_VERSION = '3.5b4';
var APP_FIREFOX = '1';
var APP_SEAMONKEY = '59';
var APP_THUNDERBIRD = '18';
var APP_SUNBIRD = '52';
var APP_FENNEC = '60';
var KEYCODE_ENTER = 13;
var addOnNotAvailableForPlatform = "%1$s is not available for %2$s.";
var error_opensearch_unsupported = "Sorry, you need a Mozilla-based browser (such as Firefox) to install a search plugin.";
var appCompatUpdateFirefox = "<a href=\"http://getfirefox.com\">Upgrade Firefox</a> to use this add-on";
var appCompatTryOldVersion = "An <a href=\"%1$s\">older version</a> may work";
var app_compat_older_firefox_only = "This add-on is for older versions of Firefox";
var appCompatUnreleasedVersion = "This add-on requires the not-yet released <a href=\"%1$s\">Firefox %2$s</a>";
var appCompatOlderVersion_or_ignore_check = "You can <a href=\"%1$s\">try an older version</a> or <a href=\"#\" onclick=\"%2$s\">ignore this check</a>";
var devcp_js_upload_alert = "You must select a file to upload.";
var addonsStatusPublic = "Public";
var addonsStatusSandbox = "In Sandbox";
var addonsStatusPending = "In Sandbox; Pending Review";
var devcp_js_img_move_down = "Move Down";
var devcpJsImgMoveUp = "Move Up";
var devcpJsOptionOwner = "Owner";
var devcpJsOptionDeveloper = "Developer";
var devcpJsOptionViewer = "Viewer";
var devcp_js_input_list_author = "List as author in public listings";
var devcpJsSureRemove = "Are you <strong>sure</strong> you wish to remove this author?";
var devcpJsRemoveAuthor = "Remove Author";
var devcpJsACancel = "Cancel";
var devcpJsAddEmail = "Please enter the account email of the author you wish to add.";
var devcp_js_img_remove_compat = "Remove Application Compatibility";
var devcpJsLicenseSelect = "Please select a license.";
var devcpJsLicenseText = "Please enter text for your license.";
var app_compat_ignore_check = "Ignore version check";
var collections_edit_submit = "Update Collection";
var collectionsEditSubmitDeletecollection = "Delete Collection";
var addonsDisplayCollectionPublishSuccess = "%1$s has been added to the %2$s collection.";
